### ISSUE TITLE
[Proposal]: context for replay contains microProxy version

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#203]
I think `ViewerContext` that would used by replay need version field.
So that microProxy could do replay with elder version of replay script.

**Comment by mike820324** [comment]
Make sense.

**Comment by chhsiao90** [comment]
The version of ViewerContext will depends on `version.py`
But I found that current version is `VERSION="0.4.0+dev"`
Could you explain how you plan for the version iteration?
That I could plan how to do the ViewerContext compatibility through different versions.
Thanks

**Comment by mike820324** [comment]
well when the tag point is tagged, the VERSION will change into current release version plus the "+dev" string. But if we release to the pypi, the pypi version will never have the +dev tag.

This is how the h11 version works, https://github.com/njsmith/h11/blob/master/h11/_version.py, which based on his comment, is following the [pep 440](https://www.python.org/dev/peps/pep-0440/).

But the version naming scheme can still be changed, since before 0.4.0, we haven't use it that often.
